baseURL: "https://tahiti-dive-management.com/"
copyright: 'Copyright © 2021-{{ year }} Tahiti Dive Management. All Rights Reserved.'
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true
enableRobotsTXT: true
languages:
  fr:
    languageName: "Français"
    weight: 20
  en:
    languageName: English
    weight: 10
params:
  disable_share: true
  background_color_class: "bg-near-black"
  featured_image_class: "contain bg-top"
  social:
    facebook:
      username: Tahiti-Dive-Management-219479998998180
  ananke.socials:
    facebook:
        username: Tahiti-Dive-Management-219479998998180
    instagram:
        username: tahitidivemanagement
    youtube:
        username: UCoYn6WcmoT_xlU6xy58vSpQ
  contact:
    email: tdm.dive@gmail.com
    phone: (+689) 87 32 66 80
  site_logo: img/tdm-logo.webp
title: Tahiti Dive Management

theme:
- github.com/theNewDynamic/gohugo-theme-ananke
module:
  imports:
  - path: github.com/hugo-mods/icons